addons:
  apt:
    packages:
      - libgmp-dev
language: c
sudo: false
cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.stack
os:
  - linux
  - osx
before_install:
  - sh tools/install-stack.sh
  - sh tools/install-ghr.sh
script:
  - stack setup
  - stack test --haddock --no-haddock-deps --ghc-options -O2 --pedantic
after_success:
  - sh tools/attach-binary.sh
