site_name: Headroom v0.3.2.0
copyright: Copyright (c) 2020 norcane

nav:
  - Home:
    - Overview: index.md
    - What's new in v0.3.2.0?: whats-new.md
  - Documentation:
      - Installation: documentation/installation.md
      - Basic Concepts: documentation/basic-concepts.md
      - Project Setup Guide: documentation/project-setup-guide.md
      - Running Headroom: documentation/running-headroom.md
      - Configuration: documentation/configuration.md
      - Extended Functionality: documentation/extended-functionality.md
      - Post-processing Functions: documentation/post-processing.md
  - License:
      - BSD-3-Clause License: license.md

theme:
  name: material
  logo: "images/norcane-logo.png"

  features:
    - tabs

  custom_dir: overrides

markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true
  - toc:
      permalink: true
  - admonition

repo_name: vaclavsvejcar/headroom
repo_url: https://github.com/vaclavsvejcar/headroom
edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/vaclavsvejcar
